name: Backend
on: [push]
defaults:
  run:
    working-directory: backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17.0.5+8' # corresponds to 17.38.21 – cp https://www.azul.com/downloads/?version=java-17-lts&architecture=x86-64-bit&package=jdk&show-old-builds=true
          distribution: 'zulu'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - run: ./gradlew test
