name: Frontend
on: [push]
defaults:
  run:
    working-directory: frontend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.18.0
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - run: npm test
